# define enumerations using the Enum base class

from enum import Enum, unique, auto

def main():
    # TODO: enums have human-readable values and types
    @unique #Will allow only unique values
    class Fruit(Enum):
        APPLE = 0
        BANANA = 1
        ORANGE = 2
        MANGO = auto() #Autogenerated
        PEAR = auto() 
         
    # TODO: enums have name and value properties
    print(f'Enum Value: {Fruit.APPLE.value}, Enum name: {Fruit.APPLE.name}')
    # TODO: print the auto-generated value
    print(Fruit.MANGO.value)
    # TODO: enums are hashable - can be used as keys
    myFruits = {}
    myFruits[Fruit.MANGO] = 'Hello Mango!'
    print(myFruits[Fruit.MANGO])

if __name__ == "__main__":
    main()
